academy/urls.py
from django.urls import path
from .views import AllCoursesView, CourseDetailView, CourseMaterialsView, MarkGraduatesView

app_name = 'academy'

urlpatterns = [
    path('',AllCoursesView.as_view(), name='dashboard'),
    path('course/<slug:slug>/',CourseDetailView.as_view(), name='course-detail'),
    path('course/<slug:slug>/<int:random_number>',CourseMaterialsView.as_view(), name='learn-course'),
    path('course/<slug:course_slug>/end',MarkGraduatesView.as_view(), name='mark-graduates'),
]

blog/urls.py
from django.urls import path
from .views import IndexView, BlogDetailView, AddCommentView

app_name = 'blog'


urlpatterns = [
    path('',IndexView.as_view(), name='index'),
    path('blog/<slug:slug>/',BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<slug:slug>/add-comment',AddCommentView.as_view(), name='add-comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogSitemap, CategorySitemap
from django.contrib.admin.sites import AdminSite
from django.shortcuts import redirect
from .views import PrivacyPolicyView

# class MyAdminSite(AdminSite):

#     def check_admin(self, request):
#         if request.user == request.user.is_authenticated():
#             return redirect('manage/admin/')
#         else:
#             return redirect('index')

#     def get_urls(self):
#         urls = super().get_urls()
#         urls += [
#             path('manage/admin/', self.admin_view(self.check_admin))
#         ]
#         return urls

sitemaps = {
    'blog':BlogSitemap,
    'category':CategorySitemap
}

urlpatterns = [
    # path('manage/admin/',MyAdminSite.get_urls),
    path('manage/admin/',admin.site.urls),
    path('academy/',include('academy.urls')),
    path('accounts/', include('allauth.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('auth/',include('profile.urls')),
    path('privacy-policy/',PrivacyPolicyView.as_view(),name='privacy'),
] + i18n_patterns(
    path('i18n/',include('django.conf.urls.i18n')),
    path('',include('blog.urls'), name=settings.LANGUAGES),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Ravshanbek Madaminov's Page AdminPanel"
admin.site.site_title = "Admin"

academy/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.utils.text import slugify
import random

    
class Course(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='course_owner')
    main_title = models.CharField(max_length=200)
    about_course = models.TextField(max_length=800)
    photo = CloudinaryField()
    students = models.ManyToManyField(User, blank=True)
    graduates = models.ManyToManyField(User, blank=True, related_name='graduates')
    slug = models.SlugField(max_length=100, blank=True)

    class Meta:
        verbose_name_plural = "Playlist Courses"
        
    def __str__(self):
            return self.main_title
    
class CourseMaterials(models.Model):
    playlist = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="materials")
    title = models.CharField(max_length=200)
    text = RichTextField()
    video = CloudinaryField(blank=True)
    link = models.URLField(blank=True)
    queue = models.IntegerField(default=0)
    random_number = models.PositiveIntegerField(default=0)
    created_time = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = "Course materials"

    def __str__(self):
        return self.title
    
@receiver(pre_save, sender=Course)
def add_course_slug(instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.main_title)
        instance.save()

@receiver(pre_save, sender=CourseMaterials)
def random_course_number(instance, *args, **kwargs):
    if instance.random_number == 0:
        instance.random_number = random.randint(100000, 999999)
        instance.save()

academy/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Course, CourseMaterials
from .tasks import add_students_to_list_task


class AllCoursesView(View):
    def get(self, request):
        courses = Course.objects.select_related()
        context = {
            'courses':courses
        }
        return render(request, 'academy/category-detail.html', context)
    
class CourseDetailView(View):
    def get(self, request, slug):
        course = Course.objects.get(slug=slug)
        materials = CourseMaterials.objects.filter(playlist__slug=course.slug).first()
        if request.user in course.students.all():
            return redirect('academy:learn-course',slug=course.slug, random_number=materials.random_number)
        context = {
            'course':course,
        }
        return render(request, 'academy/course-detail.html', context)
    
    def post(self, request, slug):
        course = Course.objects.get(slug=slug)
        materials = CourseMaterials.objects.filter(playlist__slug=course.slug).first()
        add_students_to_list_task.delay(
            user=request.user.id, slug=slug
        )
        return redirect('academy:learn-course',slug=slug, random_number=materials.random_number)

class CourseMaterialsView(View):
    def get(self, request, slug, random_number):
        course = Course.objects.get(slug=slug)
        if request.user in course.students.all():
            # filter_playlist = CourseMaterials.objects.filter(playlist__slug=course.slug).order_by('queue')
            # materials = filter_playlist.filter(random_number=random_number)
            materials = CourseMaterials.objects.filter(playlist__slug=course.slug, random_number=random_number)
            next_materials = CourseMaterials.objects.filter(playlist__slug=course.slug, random_number__gt=random_number).order_by('queue').first()
        else:
            return redirect('academy:course-detail',slug=slug)

        context = { 
            'course':course,
            'materials':materials,
            'next_materials':next_materials
        }
        return render(request, 'academy/course-materials.html', context)
    
class MarkGraduatesView(View):
    def get(self, request, course_slug):
        course = Course.objects.get(slug=course_slug)
        course.graduates.add(request.user)  
        course.save()
        return redirect('academy:dashboard')

academy/templates/academy/category-detail.html
{% extends 'base.html' %}

{% include 'navbar.html' %}
{% block title %}
<title>Category Details</title>
{% endblock title %}

{% block content %}
    {% for course in courses %}
        <a href="{% url 'academy:course-detail' course.slug %}">{{ course.main_title }}</a>
    {% endfor %}
{% endblock content %}

academy/templates/academy/category.html
{% extends 'base.html' %}

{% include 'navbar.html' %}

{% block title %}
<title>Academy</title>
{% endblock title %}

{% block content %}

    {% for category in categories %}
        <img src="{{ category.photo.url }}" width="300">
        <a href="{% url 'academy:category' category.slug %}">{{ category.name }}</a>
    {% endfor %}

{% endblock content %}

academy/templates/academy/course-detail.html
{% extends 'base.html' %}

{% include 'navbar.html' %}
{% block title %}
<title>Course Detail</title>
{% endblock title %}

{% block content %}
    <center>
        <img src="{{ course.photo.url }}" alt="" width="400">
        <h1>{{ course.main_title }}</h1>
        <p>{{ course.about_course }}</p>
        <form action="" method="post">
            {% csrf_token %}
            <button class="btn btn-primary" name="enroll-button">Enroll</button>
        </form>
    </center>
{% endblock content %}

academy/templates/academy/course-materials.html
{% extends 'base.html' %}

{% include 'navbar.html' %}
{% block title %}
{% for material in materials %}
<title>{{ material.title }}</title>
{% endfor %}
{% endblock title %}

{% block content %}
<center>
    {% for material in materials %}
        <video width="320" height="240" controls>
            {% if video %}
            <source src="{{ material.video.url }}" type="video/mp4">
            {% else %}
                <iframe width="420" height="315" src="{{ material.link }}" allowfullscreen></iframe>
            {% endif %}
            Your browser does not support the video tag.
        </video>
        <h2>{{ material.title }}</h2>
        <p>{{ material.text|safe }}</p>
        {% if next_materials %}
            <a href="{% url 'academy:learn-course' next_materials.playlist.slug next_materials.random_number %}">{{ next_materials.title }}</a>
        {% else %}
            <a href="{% url 'academy:mark-graduates' material.playlist.slug %}" class="btn btn-primary" >End Course</a>
        {% endif %}
    {% endfor %}
</center>
{% endblock content %}