blog/urls.py
from django.urls import path
from .views import IndexView, BlogDetailView, AddCommentView

app_name = 'blog'


urlpatterns = [
    path('',IndexView.as_view(), name='index'),
    path('blog/<slug:slug>/',BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<slug:slug>/add-comment',AddCommentView.as_view(), name='add-comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogSitemap, CategorySitemap
from django.contrib.admin.sites import AdminSite
from django.shortcuts import redirect
from .views import PrivacyPolicyView

# class MyAdminSite(AdminSite):

#     def check_admin(self, request):
#         if request.user == request.user.is_authenticated():
#             return redirect('manage/admin/')
#         else:
#             return redirect('index')

#     def get_urls(self):
#         urls = super().get_urls()
#         urls += [
#             path('manage/admin/', self.admin_view(self.check_admin))
#         ]
#         return urls

sitemaps = {
    'blog':BlogSitemap,
    'category':CategorySitemap
}

urlpatterns = [
    # path('manage/admin/',MyAdminSite.get_urls),
    path('manage/admin/',admin.site.urls),
    path('academy/',include('academy.urls')),
    path('accounts/', include('allauth.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('auth/',include('profile.urls')),
    path('privacy-policy/',PrivacyPolicyView.as_view(),name='privacy'),
] + i18n_patterns(
    path('i18n/',include('django.conf.urls.i18n')),
    path('',include('blog.urls'), name=settings.LANGUAGES),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Ravshanbek Madaminov's Page AdminPanel"
admin.site.site_title = "Admin"

portfolio/urls.py
from django.urls import path
from .views import DashboardView, ProjectDetailView

app_name = 'portfolio'

urlpatterns = [
    path('',DashboardView.as_view(), name='dashboard'),
    path('<int:pk>',ProjectDetailView.as_view(), name='project-detail'),
]

portfolio/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField
import datetime

class Category(models.Model):
    category_name = models.CharField(max_length=40)

    def __str__(self):
        return self.category_name

class Project(models.Model):
    name = models.CharField(max_length=200)
    about_project = RichTextField()
    link = models.URLField()
    preview_photo = CloudinaryField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    views = models.IntegerField(default=0)
    added_date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Projects"

    def __str__(self):
        return self.name
    
class Experience(models.Model):
    company_name = models.CharField(max_length=100, blank=True)
    role = models.CharField(max_length=30)
    description = models.TextField(max_length=300, blank=True)
    location = models.URLField(blank=True)
    years = models.DateField(auto_now_add=False)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Experience"

    def __str__(self):
        return f"{self.company_name}-{self.years}"
    
class Education(models.Model):
    company_name = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    location = models.URLField(blank=True)
    description = models.TextField(max_length=100)
    years = models.DateField(auto_now_add=False)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Education"

    def __str__(self):
        return self.company_name

portfolio/views.py
from django.shortcuts import render
from django.views import View

from .models import Project, Experience, Education, Category

class DashboardView(View):
    def get(self, request):
        categories = Category.objects.all()
        projects = Project.objects.select_related()[:6]
        experience = Experience.objects.all().order_by('-years')[:5]
        education = Education.objects.all().order_by('-years')[:5]

        context = {
            'categories':categories,
            'projects':projects,
            'experiences':experience,
            'educations':education
        }
        return render(request, 'portfolio/portfolio-masonry.html',context)
    
class ProjectDetailView(View):
    def get(self, request, pk):

        project = Project.objects.get(id=pk)
        project.views += 1
        project.save()
        context = {
            'project':project
        }

        return render(request, 'portfolio/portfolio-single-1.html', context)

portfolio/templates/portfolio/index.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ravshanbek's Portfolio</title>

    <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/unicons.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.theme.default.min.css' %}">

    <!-- MAIN STYLE -->
    <link rel="stylesheet" href="{% static 'portfolio/css/tooplate-style.css' %}">
    
<!--

Tooplate 2115 Marvel

https://www.tooplate.com/view/2115-marvel

-->
  </head>
  <body>

    <!-- MENU -->
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blog:index' %}"><i class='uil uil-user'></i> Ravshanenergy</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a href="#about" class="nav-link"><span data-hover="About">About</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#project" class="nav-link"><span data-hover="Projects">Projects</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#resume" class="nav-link"><span data-hover="Resume">Resume</span></a>
                    </li>
                </ul>

                <ul class="navbar-nav ml-lg-auto">
                    <div class="ml-lg-4">
                      <div class="color-mode d-lg-flex justify-content-center align-items-center">
                        <i class="color-mode-icon"></i>
                        Color mode
                      </div>
                    </div>
                </ul>
            </div>
        </div>
    </nav>

    <!-- ABOUT -->
    <section class="about full-screen d-lg-flex justify-content-center align-items-center" id="about">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-7 col-md-12 col-12 d-flex align-items-center">
                    <div class="about-text">
                        <small class="small-text">Welcome to <span class="mobile-block"> portfolio section!</span></small>
                        <h1 class="animated animated-text">
                            <span class="mr-2">My full name is Ravshanbek Madaminov</span>
                        </h1>

                        <p>Building a successful product is a challenge. I am highly energetic in creating APIs and web development.</p>
                        
                        <div class="custom-btn-group mt-4">
                          <a href="#" class="btn mr-lg-2 custom-btn"><i class='uil uil-file-alt'></i> Download Resume</a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-5 col-md-12 col-12">
                    <div class="about-image svg">
                        <img src="{% static 'portfolio/images/undraw/undraw_software_engineer_lvl5.svg' %}" class="img-fluid" alt="svg image">
                    </div>
                </div>

            </div>
        </div>
    </section>

    <!-- PROJECTS -->
    <section class="project py-5" id="project">
        <div class="container">
                
                <div class="row">
                  <div class="col-lg-11 text-center mx-auto col-12">

                      <div class="col-lg-8 mx-auto">
                        <h2>My projects</h2>
                      </div>

                      <div class="owl-carousel owl-theme">
                        {% for project in projects %}
                          <div class="item">
                            <div class="project-info">  
                              <a href="{% url 'portfolio:project-detail' project.name %}">
                                <img src="{{ project.preview_photo.url }}" class="img-responsive" alt="project image">
                              </a>
                            </div>
                          </div>
                        {% endfor %}
                      </div>

                  </div>
                </div>
        </div>
    </section>

    <!-- FEATURES -->
    <section class="resume py-5 d-lg-flex justify-content-center align-items-center" id="resume">
        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-12">
                  <h2 class="mb-4">Experiences</h2>
                    <div class="timeline">
                        {% for experience in experiences %}
                            <div class="timeline-wrapper">
                                <div class="timeline-yr">
                                    <span>{{ experience.years|date:'Y' }}</span>
                                </div>
                                <div class="timeline-info">
                                    <h3><span>{{ experience.role }}</span><small>{{ experience.company_name }}</small></h3>
                                    <p>{{ experience.description }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="col-lg-6 col-12">
                  <h2 class="mb-4 mobile-mt-2">Educations</h2>

                    <div class="timeline">
                        {% for education in educations %}
                            <div class="timeline-wrapper">
                                <div class="timeline-yr">
                                    <span>{{ education.years|date:'Y' }}</span>
                                </div>
                                <div class="timeline-info">
                                    <h3><span>{{ education.role }}</span><small>{{ education.company_name }}</small></h3>
                                    <p>{{ education.description }}</p>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
                
            </div>
        </div>
    </section>

    <!-- FOOTER -->
     <footer class="footer py-5">
          <div class="container">
               <div class="row">

                    <div class="col-lg-12 col-12">                                
                        <p class="copyright-text text-center">Copyright &copy; 2023 Ravshanenergy . All rights reserved</p>
                    </div>
                    
               </div>
          </div>
     </footer>

    <script src="{% static 'portfolio/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'portfolio/js/popper.min.js' %}"></script>
    <script src="{% static 'portfolio/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'portfolio/js/Headroom.js' %}"></script>
    <script src="{% static 'portfolio/js/jQuery.headroom.js' %}"></script>
    <script src="{% static 'portfolio/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'portfolio/js/smoothscroll.js' %}"></script>
    <script src="{% static 'portfolio/js/custom.js' %}"></script>

  </body>
</html>

portfolio/templates/portfolio/portfolio-masonry.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
<title>My projects</title>
{% endblock title %}

{% block meta %}

{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
    <!-- Button - Back to top -->
    <a href="#" class="btn-back-to-top scrollto btn btn-icon btn-primary shadow-light mb-4 mr-4" tabindex="-1">
      <i class="fas fa-chevron-up btn-icon-inner"></i>
    </a>

    <section class="bg-primary py-9 py-lg-10">
      <div class="container my-9 my-lg-10">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center text-white">

            <h2 class="h1 mb-3">My projects</h2>
            <p class="mb-6">You can easily see all of my projects here!</p>
            <nav class="masonry-filter">
              <a href="" class="btn btn-sm btn-soft-white m-1 px-4 active" data-filter="*">All</a>
              {% for category in categories %}
                <a href="" class="btn btn-sm btn-soft-white m-1 px-4" data-filter=".{{ category.category_name|lower }}">{{ category.category_name }}</a>
              {% endfor %}
            </nav>

          </div>
        </div>
      </div>
      <div class="shape-advanced shape-bottom">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 20" class="fill-white" preserveAspectRatio="none">
          <path d="M 0 0 C 200 20 400 18 500 18 C 600 18 800 20 1000 0 L 1000 20 L 0 20 L 0 0 Z"/>
        </svg>
      </div>
    </section>

    <!-- Website Content -->
    <div class="website-content mt-n8 mt-lg-n10">
      <div class="website-content-inner pb-8 pb-lg-10">
        <div class="website-content-box" id="services">
          <div class="website-content-box-inner py-6 py-lg-8 py-xl-10">
            <div class="container-fluid px-6 px-lg-8 px-xl-10">

              <div class="masonry-container row m-n4">
                {% for project in projects %}
                  <div class="col-sm-6 col-md-4 p-4 masonry-item {{ project.category.category_name|lower }}">
                    <a class="card border-0" href="{% url 'portfolio:project-detail' project.id %}">
                      <div class="card-zoom">
                        <img class="card-img" src="{{ project.preview_photo.url }}" alt="">
                      </div>
                      <div class="card-footer px-0 pb-0">
                        <p class="small text-uppercase mb-1 text-muted">{{ project.category.category_name }}</p>
                        <h4 class="h5 text-dark mb-0">{{ project.name }}</h4>
                      </div>
                    </a>
                  </div>
                {% endfor %}

              </div>

              <div class="bg-light rounded-lg mt-6 mt-lg-8 p-5 p-sm-8 p-lg-10 text-center d-none d-sm-block">
                <h3 class="mb-5 mb-md-7">Start a project. Get in touch</h3>
                <a href="https://t.me/rmdeveloper" class="btn btn-primary px-8">Hire Me</a>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

portfolio/templates/portfolio/portfolio-single-1.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
<title>{{ project.name }}</title>
{% endblock title %}

{% block meta %}

{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<!-- Button - Back to top -->
    <a href="#" class="btn-back-to-top scrollto btn btn-icon btn-primary shadow-light mb-4 mr-4" tabindex="-1">
      <i class="fas fa-chevron-up btn-icon-inner"></i>
    </a>

    <section class="bg-primary py-9 py-lg-10">
      <div class="container my-9 my-lg-10">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center text-white">

            <h2 class="h1 mb-0">{{ project.name }}</h2>

          </div>
        </div>
      </div>
      <div class="shape-advanced shape-bottom">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 20" class="fill-white" preserveAspectRatio="none">
          <path d="M 0 0 C 200 20 400 18 500 18 C 600 18 800 20 1000 0 L 1000 20 L 0 20 L 0 0 Z"/>
        </svg>
      </div>
    </section>

    <!-- Website Content -->
    <div class="website-content mt-n8 mt-lg-n10">
      <div class="website-content-inner pb-8 pb-lg-10">
        <div class="website-content-box">
          <div class="website-content-box-inner py-6 py-lg-8 py-xl-10">
            <div class="container-fluid px-6 px-lg-8 px-xl-10">

              <div class="row mb-6 mb-lg-8">
                <div class="col-lg-8 mb-5 mb-lg-0">
                  <h5>About the project</h5>
                  <p>{{ project.about_project }}</p>
                </div>
                <div class="col-lg-4 text-left text-lg-right">
                  <ul class="list-unstyled mb-0">  
                    <li>{{ project.added_date }}</li>
                    <li><a href="#" rel="tag" class="text-dark">{{ project.category.category_name }}</a></li>
                    <li>{{ project.views }} Views</li>
                    <!-- <li><a href="#" class="text-dark">147 Likes</a></li> -->
                  </ul>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-9 mx-auto text-center">

                  <h3 class="mb-7">Start a project. Get in touch</h3>
                  <a href="https://t.me/rmdeveloper" class="btn btn-primary px-6">Hire Me</a>

                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

portfolio/templates/portfolio/project-detail.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ravshanbek's Portfolio</title>

    <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/unicons.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.theme.default.min.css' %}">

    <!-- MAIN STYLE -->
    <link rel="stylesheet" href="{% static 'portfolio/css/tooplate-style.css' %}">
    
<!--

Tooplate 2115 Marvel

https://www.tooplate.com/view/2115-marvel

-->
  </head>
  <body>

    <!-- MENU -->
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blog:index' %}"><i class='uil uil-user'></i> Ravshanenergy</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a href="#about" class="nav-link"><span data-hover="About">About</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#project" class="nav-link"><span data-hover="Projects">Projects</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#resume" class="nav-link"><span data-hover="Resume">Resume</span></a>
                    </li>
                </ul>

                <ul class="navbar-nav ml-lg-auto">
                    <div class="ml-lg-4">
                      <div class="color-mode d-lg-flex justify-content-center align-items-center">
                        <i class="color-mode-icon"></i>
                        Color mode
                      </div>
                    </div>
                </ul>
            </div>
        </div>
    </nav>

    <section class="project py-5" id="project">
        <div class="container">
                
                <div class="row">
                  <div class="col-lg-11 text-center mx-auto col-12">

                      <div class="col-lg-8 mx-auto">
                        <h2>My projects</h2>
                      </div>

                      <div class="col">
                        <div class="item">
                            <div class="project-info">  
                                <img src="{{ project.preview_photo.url }}" class="img-responsive" alt="project image">
                            </div>
                            <p>{{ project.about_project|urlize }}</p>
                            <a href="{{ project.link }}">Project Link</a>
                        </div>
                      </div>

                  </div>
                </div>
        </div>
    </section>

    <!-- FOOTER -->
    <footer class="footer py-5">
        <div class="container">
             <div class="row">

                  <div class="col-lg-12 col-12">                                
                      <p class="copyright-text text-center">Copyright &copy; 2023 Ravshanenergy . All rights reserved</p>
                  </div>
                  
             </div>
        </div>
   </footer>

  <script src="{% static 'portfolio/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'portfolio/js/popper.min.js' %}"></script>
  <script src="{% static 'portfolio/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'portfolio/js/Headroom.js' %}"></script>
  <script src="{% static 'portfolio/js/jQuery.headroom.js' %}"></script>
  <script src="{% static 'portfolio/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'portfolio/js/smoothscroll.js' %}"></script>
  <script src="{% static 'portfolio/js/custom.js' %}"></script>

</body>
</html>