blog/urls.py
from django.urls import path
from .views import IndexView, BlogDetailView, AddCommentView

app_name = 'blog'


urlpatterns = [
    path('',IndexView.as_view(), name='index'),
    path('blog/<slug:slug>/',BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<slug:slug>/add-comment',AddCommentView.as_view(), name='add-comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogSitemap, CategorySitemap
from django.contrib.admin.sites import AdminSite
from django.shortcuts import redirect
from .views import PrivacyPolicyView

# class MyAdminSite(AdminSite):

#     def check_admin(self, request):
#         if request.user == request.user.is_authenticated():
#             return redirect('manage/admin/')
#         else:
#             return redirect('index')

#     def get_urls(self):
#         urls = super().get_urls()
#         urls += [
#             path('manage/admin/', self.admin_view(self.check_admin))
#         ]
#         return urls

sitemaps = {
    'blog':BlogSitemap,
    'category':CategorySitemap
}

urlpatterns = [
    # path('manage/admin/',MyAdminSite.get_urls),
    path('manage/admin/',admin.site.urls),
    path('academy/',include('academy.urls')),
    path('accounts/', include('allauth.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('auth/',include('profile.urls')),
    path('privacy-policy/',PrivacyPolicyView.as_view(),name='privacy'),
] + i18n_patterns(
    path('i18n/',include('django.conf.urls.i18n')),
    path('',include('blog.urls'), name=settings.LANGUAGES),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Ravshanbek Madaminov's Page AdminPanel"
admin.site.site_title = "Admin"

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from cloudinary import CloudinaryImage
from .signals import add_gpt_response


class Category(models.Model):
    name = models.CharField(max_length=25)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Category"

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True, max_length=200)
    body = RichTextField(blank=True)
    preview_image = CloudinaryField()
    category = models.ManyToManyField(Category, related_name='blogs')
    meta_description = models.CharField(max_length=160)
    meta_keyword = models.TextField()
    views = models.IntegerField(default=0)
    likes = models.ManyToManyField(User, related_name='post_likes')
    added_date = models.DateField(auto_now_add=True)
    estimated_read_time = models.IntegerField(default=2)

    class Meta:
        verbose_name_plural = "Blog"

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        super(Blog,self).save(*args, **kwargs)

        self.preview_image = CloudinaryImage(str(self.preview_image)).image(height=200, width=150, crop="lfill")
        print(self.preview_image)
    
    def number_of_likes(self):
        return self.likes.count()
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=200)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=Category)
def post_save_category(instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)
        instance.save()
    
@receiver(post_save, sender=Blog)
def pre_save_blog(instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)
        instance.save()

add_gpt_response(instance=Blog)

blog/forms.py
from django.forms import ModelForm, Textarea
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['blog','user',]

        fields = [
            'comment',
        ]

        labels = {
            'comment':'',
        }

        widgets = {
            'comment':Textarea(attrs={'id':"comment", 'class':"form-control", 'name':"comment", 'cols':"45", 'rows':"8", 'aria-required':"true", 'placeholder':"Comment"}),
        }

blog/views.py
from django.shortcuts import render, redirect
from django.views import View

from .models import Blog, Comment
from .tasks import add_like_to_blog_task
from .forms import CommentForm

class IndexView(View):
    def get(self, request):
        if request.user.is_authenticated:
            blogs = Blog.objects.select_related()[:12]
            context = {
                'blogs':blogs,
            }
        else:
            return redirect('signin')
        return render(request, 'blog/index.html', context)
        # if request.user.is_authenticated:
        #     response.set_cookie(request.user.username,f'Bu {request.user.username} nomli foydalanuvchi')
        # else:
        #     return redirect('signin')
        # return response
     
class BlogDetailView(View):
    def get(self, request, slug):
        if request.user.is_authenticated:
            blog = Blog.objects.get(slug=slug)
            comments = Comment.objects.filter(blog=blog)
            blog.views += 1
            blog.save()
            #blogs = Blog.objects.filter(category__name=blog.category.first()).exclude(slug=blog.slug)[:3]
            
            form = CommentForm

            context = {
                'blog':blog,
                'comments':comments,
                'number_of_likes':blog.number_of_likes,
                'likes_number':blog.likes.count(),
                'likes':blog.likes,
                'form':form
            }
        
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
        else:
            return redirect('signin')
        return render(request, 'blog/blog-single.html', context)

    def post(self, request, slug):
        add_like_to_blog_task.delay(
            user=request.user.id, slug=slug
        )
        
        return redirect('blog:blog-detail',slug=slug)
    
class AddCommentView(View):
    def post(self, request, slug):
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.blog = Blog.objects.get(slug=slug)
            data.user = request.user
            data.save()
            return redirect('blog:blog-detail',slug=slug)

blog/templates/blog/blog-single.html
{% extends 'base.html' %}
{% load i18n %}
{% load social_share %}

{% block title %}
<title>{{ blog.title }}</title>
{% endblock title %}

{% block meta %}
<meta name="description" content="{{ blog.meta_description }}">
<meta name="author" content="Ravshanbek Madaminov">
<meta name="keywords" content="{{ blog.meta_keyword }}">
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}


<!-- Button - Back to top -->
    <a href="#" class="btn-back-to-top scrollto btn btn-icon btn-primary shadow-light mb-4 mr-4" tabindex="-1">
      <i class="fas fa-chevron-up btn-icon-inner"></i>
    </a>

    <section class="bg-primary py-9 py-lg-10">
      <div class="container my-9 my-lg-10">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center text-white">

            <h2 class="h1">{{ blog.title }}</h2>
            <p>{{ blog.added_date|date:"c" }} - {{ blog.estimated_read_time }} {% if blog.estimated_read_time > 1 %} minutes {% else %} minute {% endif %} read</p>

          </div>
        </div>
      </div>
      <div class="shape-advanced shape-bottom">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 20" class="fill-white" preserveAspectRatio="none">
          <path d="M 0 0 C 200 20 400 18 500 18 C 600 18 800 20 1000 0 L 1000 20 L 0 20 L 0 0 Z"/>
        </svg>
      </div>
    </section>

    <!-- Website Content -->
    <div class="website-content mt-n8 mt-lg-n10">
      <div class="website-content-inner pb-8 pb-lg-10">
        <div class="website-content-box">
          <div class="website-content-box-inner py-6 py-lg-8 py-xl-10">
            <div class="container-fluid px-6 px-lg-8 px-xl-10">

              <article class="article">
                <p>{{ blog.body|safe }}</p>
              </article>

              <hr class="my-7"/>

              <h4 class="mb-7">Comments</h4>
              <ul class="article-comments">
                {% for comment in comments %}
                  <li>

                    <div class="d-flex align-items-center mb-2">
                      <div class="avatar mr-4">
                        <img src="assets/images/avatars/avatar-2.jpg" alt="" class="avatar-img">
                      </div>
                      <div>
                        <b class="fn">{% if comment.user.first_name %} {{ comment.user.first_name }} {{ comment.user.last_name }} {% else %} {{ comment.user.username }} {% endif %}</b>
                        <div class="small text-muted">{{ comment.added_date }}</div>
                      </div>
                    </div>
                    <p>{{ comment.comment }}</p>
                    <!-- <a href="#">Reply</a> -->

                  
                  </li>
                {% endfor %}
              </ul>

              <hr class="my-7"/>

              <h4 class="mb-5">Add comment</h4>
              {% if request.user.is_authenticated %}
                <form action="{% url 'blog:add-comment' blog.slug %}" method="post">
                  {% csrf_token %}
                  <div class="form-row">
                    <div class="col-12 form-group">
                      {{ form.as_p }}
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary" id="submit" name="submit">Submit</button>
                </form>
              {% else %}
                <p>You can't add comments because of permissions</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block meta %}
<meta name="description" content="Tips, instructions and video tutorials for dreamers">
<meta name="author" content="Ravshanbek Madaminov">
<meta name="keywords" content="Ravshanbek Madaminov, Ravshanbek's Blog, Ravshanenergy uz, Ravshanenergy.uz, Python, JavaScript, Java, PHP, Programming, How to, What is">
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}
    
<!-- Begin Site Title
================================================== -->
<div class="container">
	<div class="mainheading">
		<h1 class="sitetitle">Ravshanbek's Blog</h1>
		<p class="lead">
			{% blocktrans %}Tips, instructions and video tutorials for dreamers{% endblocktrans %}
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin List Posts
	================================================== -->
	<section class="recent-posts">
		<div class="section-title">
			<h2><span>{% blocktrans %}All Stories{% endblocktrans %}</span></h2>
		</div>
		<div class="card-columns listrecent">
			{% for blog in blogs %}
				<!-- begin post -->
				<div class="card">
					<a href="{% url 'blog:blog-detail' blog.slug %}">
						<img class="img-fluid" src="{{ blog.preview_image.url }}" alt="">
					</a>
					<div class="card-block">
						<h2 class="card-title"><a href="{% url 'blog:blog-detail' blog.slug %}">{{ blog.title }}</a></h2>
						<h4 class="card-text">{{ blog.subtitle }}</h4>
						<div class="metafooter">
							<div class="wrapfooter">
								<span class="meta-footer-thumb">
								</span>
								<span class="author-meta">
								<span class="post-date">{{ blog.added_date }}</span><span class="dot"></span><span class="post-read">{{ blog.estimated_read_time }} min read</span>
								</span>
							</div>
						</div>
					</div>
				</div>
				<!-- end post -->
			{% endfor %}

		</div>
	</section>
	<!-- End List Posts
	================================================== -->

	<nav aria-label="Page navigation example">
			<ul class="pagination justify-content-center">

				{% if blogs.has_previous %}
					<li><a href="?page={{blogs.previous_page_number}}" class="btn page-link"
							data-page="{{blogs.previous_page_number}}">&#10094; {% blocktrans %}Prev{% endblocktrans %}</a></li>
				{% endif %}


				{% for page in custom_range %}

					{% if page == blogs.number%}
					<li><a href="?page={{page}}" class="btn page-link btn--sub" data-page="{{page}}">{{page}}</a></li>
					{% else %}
					<li><a href="?page={{page}}" class="btn page-link" data-page="{{page}}">{{page}}</a></li>
					{% endif %}
				{% endfor %}

				{% if blogs.has_next %}
					<li><a href="?page={{blogs.next_page_number}}" class="btn page-link"
							data-page="{{blogs.next_page_number}}">{% blocktrans %}Next{% endblocktrans %} &#10095;</a></li>
				{% endif %}

			</ul>
	</nav>
	

{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>RavshanEnergy - Home Page</title>
{% endblock title %}

{% block meta %}
<meta name="description" content="Tips, instructions and video tutorials for dreamers">
<meta name="author" content="Ravshanbek Madaminov">
<meta name="keywords" content="Ravshanbek Madaminov, Ravshanbek's Blog, Ravshanenergy uz, Ravshanenergy.uz, Python, JavaScript, Java, PHP, Programming, How to, What is">
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}

<section id="home" class="bg-primary py-8 py-lg-10">
    <div class="container my-8 my-lg-10">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center text-white">

          <h1 class="h1 text-white mb-7 ">Welcome!</h1>
          <h2 class="h5 text-white mb-7">Blogs, projects and courses for dreamers</h2>
          <a href="about-me.html" class="btn btn-soft-white d-block d-sm-inline-block scrollto">About me</a>

        </div>
      </div>
    </div>
    <div class="shape-advanced shape-bottom">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 20" class="fill-white" preserveAspectRatio="none">
        <path d="M 0 0 C 200 20 400 18 500 18 C 600 18 800 20 1000 0 L 1000 20 L 0 20 L 0 0 Z"/>
      </svg>
    </div>
  </section>

  <section id="slide-demo" class="pt-8 pt-xl-10 pb-0">
    <div class="container">
      <h2 class="text-center mb-7">{% blocktrans %}Blogs{% endblocktrans %}</h2>
      <div class="row m-n4">
        {% for blog in blogs %}
            <div class="col-12 col-sm-6 col-lg-4 p-4">
                <a class="card" href="{% url 'blog:blog-detail' blog.slug %}">
                    <img class="card-img-top" src="{{ blog.preview_image.url }}" alt="Unsupported image">
                    <div class="card-body text-center text-body">
                    <p>{{ blog.title }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}  
      </div>
    </div>
  </section>

  <section class="pt-8 pt-xl-10 pb-0">
    <div class="container mb-n8 mb-xl-n10">
      <div class="bg-primary rounded px-7 py-8 py-xl-10 text-white text-center">
        <div class="w-lg-75 w-xl-50 mx-auto">
          <h2 class="mb-5">Start with our services</h2>
          <p class="lead mb-7">We can easily build any web-app for you and your service!</p>
          <a href="https://t.me/rmdeveloper" rel="nofollow noopener" class="btn btn-white mr-md-3">Contact</a>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

blog/templates/blog/post.html
{% extends 'base.html' %}
{% load i18n %}
{% load social_share %}

{% block title %}
<title>{{ blog.title }}</title>
{% endblock title %}

{% block meta %}
<meta name="description" content="{{ blog.meta_description }}">
<meta name="author" content="Ravshanbek Madaminov">
<meta name="keywords" content="{{ blog.meta_keyword }}">
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}
<!-- Begin Article
================================================== -->
<div class="container">
	<div class="row">

		<div class="col-md-2 col-xs-12">
			<div class="share">
				<p>
					Share
				</p>
				<ul>
					<li>
						{% post_to_facebook object_or_url "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><path d='M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z'/></svg>" %}
					</li>
					<li>
						{% post_to_twitter "Useful blog: {{ object.title }}. Check it out!" object_or_url "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><path d='M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z'/></svg>" %}
					</li>
					<li>
						{% post_to_telegram "Useful blog: {{ object.title }}. Check it out!" object_or_url "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 496 512'><path d='M248,8C111.033,8,0,119.033,0,256S111.033,504,248,504,496,392.967,496,256,384.967,8,248,8ZM362.952,176.66c-3.732,39.215-19.881,134.378-28.1,178.3-3.476,18.584-10.322,24.816-16.948,25.425-14.4,1.326-25.338-9.517-39.287-18.661-21.827-14.308-34.158-23.215-55.346-37.177-24.485-16.135-8.612-25,5.342-39.5,3.652-3.793,67.107-61.51,68.335-66.746.153-.655.3-3.1-1.154-4.384s-3.59-.849-5.135-.5q-3.283.746-104.608,69.142-14.845,10.194-26.894,9.934c-8.855-.191-25.888-5.006-38.551-9.123-15.531-5.048-27.875-7.717-26.8-16.291q.84-6.7,18.45-13.7,108.446-47.248,144.628-62.3c68.872-28.647,83.183-33.623,92.511-33.789,2.052-.034,6.639.474,9.61,2.885a10.452,10.452,0,0,1,3.53,6.716A43.765,43.765,0,0,1,362.952,176.66Z'/></svg>" %}
					</li>
				</ul>
				<div class="sep">
				</div>
				<ul>
					{% if user.is_authenticated %}
						<li>
							<form action="{% url 'blog:blog-detail' blog.slug %}" method="GET">{% csrf_token %}
								{% if likes %}
									<button type="submit" name="blogpost_id" value="{{ blog.id }}" class="btn btn-secondary">
										<i class="fas fa-thumbs-up"></i>
									</button>
								{% else %}
									<button type="submit" name="blogpost_id" value="{{ blog.id }}" class="btn btn-secondary">
										<i class="fas fa-thumbs-up"></i>
									</button>
								{% endif %}	
							</form>
						</li>
					{% else  %}
						<button type="submit" name="blogpost_id" value="{{ blog.id }}" class="btn btn-secondary disabled">
							<i class="fas fa-thumbs-up"></i>
						</button>
					{% endif %}
					<p>{{ likes_number }} Like{{ likes_number|pluralize }}</p>
				</ul>
			</div>
		</div>
		<!-- End Fixed Left Share -->

		<!-- Begin Post -->
		<div class="col-md-8 col-md-offset-2 col-xs-12">
			<div class="mainheading">
				<h1 class="posttitle">{{ blog.title }}</h1>
				<p class="text-secondary">{% blocktrans %}Posted on {% endblocktrans %} {{ blog.added_date }}</p>
			</div>

			<!-- Begin Featured Image -->
			<img class="featured-image img-fluid" src="{{ blog.preview_image.url }}" alt="">
			<!-- End Featured Image -->

			<!-- Begin Post Content -->
			<div class="article-post">
				{{ blog.body|safe|linebreaks }}
			</div>
			<!-- End Post Content -->

			<!-- Begin Tags -->
			<div class="after-post-tags">
				<ul class="tags">
					{% for category in blog.category.all %}
						<li><a href="#">{{ category.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<!-- End Tags -->

		</div>
		<!-- End Post -->

	</div>
</div>
<!-- End Article
================================================== -->

<div class="hideshare"></div>

<!-- Begin Related
================================================== -->
<div class="graybg">
	<div class="container">
		<h3>{% blocktrans %}Related{% endblocktrans %}</h3>
		<div class="row listrecent listrelated">
            {% for blog in blogs %}
                <!-- begin post -->
                <div class="col-md-4">
                    <div class="card">
                        <a href="{% url 'blog:blog-detail' blog.slug %}">
                        <img class="img-fluid img-thumb" src="{{ blog.preview_image.url }}" alt="">
                        </a>
                        <div class="card-block">
                            <h2 class="card-title"><a href="{% url 'blog:blog-detail' blog.slug %}">{{ blog.title }}</a></h2>
                            <div class="metafooter">
                                <div class="wrapfooter">
                                    <span class="meta-footer-thumb">
                                    </span>
                                    <span class="author-meta">
                                    <span class="post-date">{{ blog.added_date }}</span><span class="dot"></span><span class="post-read">{{ blog.estimated_read_time }} min read</span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end post -->
            {% endfor %}
		</div>
	</div>
</div>
<!-- End Related Posts
================================================== -->

<!-- Begin AlertBar
================================================== -->
<!-- <div class="alertbar">
	<div class="container text-center">
		<img src="assets/img/logo.png" alt=""> &nbsp; Never miss a <b>story</b> from us, get weekly updates in your inbox. <a href="#" class="btn subscribe">Get Updates</a>
	</div>
</div> -->
<!-- End AlertBar
================================================== -->

{% endblock content %}