academy/urls.py
from django.urls import path
from .views import AllCoursesView, CourseDetailView, CourseMaterialsView, MarkGraduatesView

app_name = 'academy'

urlpatterns = [
    path('',AllCoursesView.as_view(), name='dashboard'),
    path('course/<slug:slug>/',CourseDetailView.as_view(), name='course-detail'),
    path('course/<slug:slug>/<int:random_number>',CourseMaterialsView.as_view(), name='learn-course'),
    path('course/<slug:course_slug>/end',MarkGraduatesView.as_view(), name='mark-graduates'),
]

blog/urls.py
from django.urls import path
from .views import IndexView, BlogDetailView, AddCommentView

app_name = 'blog'


urlpatterns = [
    path('',IndexView.as_view(), name='index'),
    path('blog/<slug:slug>/',BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<slug:slug>/add-comment',AddCommentView.as_view(), name='add-comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogSitemap, CategorySitemap
from django.contrib.admin.sites import AdminSite
from django.shortcuts import redirect
from .views import PrivacyPolicyView

# class MyAdminSite(AdminSite):

#     def check_admin(self, request):
#         if request.user == request.user.is_authenticated():
#             return redirect('manage/admin/')
#         else:
#             return redirect('index')

#     def get_urls(self):
#         urls = super().get_urls()
#         urls += [
#             path('manage/admin/', self.admin_view(self.check_admin))
#         ]
#         return urls

sitemaps = {
    'blog':BlogSitemap,
    'category':CategorySitemap
}

urlpatterns = [
    # path('manage/admin/',MyAdminSite.get_urls),
    path('manage/admin/',admin.site.urls),
    path('academy/',include('academy.urls')),
    path('accounts/', include('allauth.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('auth/',include('profile.urls')),
    path('privacy-policy/',PrivacyPolicyView.as_view(),name='privacy'),
] + i18n_patterns(
    path('i18n/',include('django.conf.urls.i18n')),
    path('',include('blog.urls'), name=settings.LANGUAGES),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Ravshanbek Madaminov's Page AdminPanel"
admin.site.site_title = "Admin"

portfolio/urls.py
from django.urls import path
from .views import DashboardView, ProjectDetailView

app_name = 'portfolio'

urlpatterns = [
    path('',DashboardView.as_view(), name='dashboard'),
    path('<int:pk>',ProjectDetailView.as_view(), name='project-detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en-US" class="no-js">
    {% load static %}
    {% load i18n %}
<head>
    {% block title %}
    <!-- Title -->
    <title>{% blocktrans %}Ravshanbek's Blog - About Technology and Programming!{% endblocktrans %}</title>
    <meta name="google-site-verification" content="I9pKMp1bWMrl1EC20aKYvjmGIzqSP6mXffAEs0jZ_iI" />
    {% endblock title %}

    <!-- Required Meta Tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta %}

    {% endblock meta %}

    <!-- Libs CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/dist/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/all.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/themify-icons/css/themify-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/slick/slick.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/featherlight/featherlight.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/featherlight/featherlight.gallery.min.css' %}" type="text/css">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&amp;family=Open+Sans:wght@300;400;600;700&amp;display=swap" rel="stylesheet">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/utilities.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

  </head>
  <body>

    {% block content %}

    {% endblock content %}

    <footer class="position-relative py-9 py-lg-12 bg-dark text-gray-500">
        <div class="shape-advanced shape-top shape-outside">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 20" class="fill-dark" preserveAspectRatio="none">
            <path d="M 0 0 C 200 20 400 18 500 18 C 600 18 800 20 1000 0 L 1000 20 L 0 20 L 0 0 Z"/>
          </svg>
        </div>
        <div class="container px-xl-10 pt-8 pt-xl-10">
          <div class="row">
            <div class="col-lg-10 mx-auto text-center">
              <img src="assets/images/logo-white.png" alt="" class="img-fluid mb-5">
              <p class="text-gray-400 mb-5">All of this stuffs belongs to me</p>
              <ul class="list-inline mb-8">
  
                <li class="list-inline-item mx-0">
                  <a class="btn btn-sm btn-icon btn-soft-secondary text-gray-400" href="https://www.facebook.com/ravshanbek.madaminov.39/" tabindex="0">
                    <i class="fab fa-facebook-f btn-icon-inner"></i>
                  </a>
                </li>
  
                <li class="list-inline-item mx-0">
                  <a class="btn btn-sm btn-icon btn-soft-secondary text-gray-400" href="https://www.instagram.com/ravshanenergy.uz/" tabindex="0">
                    <i class="fab fa-instagram btn-icon-inner"></i>
                  </a>
                </li>
  
                <li class="list-inline-item mx-0">
                  <a class="btn btn-sm btn-icon btn-soft-secondary text-gray-400" href="https://www.linkedin.com/in/ravshanbek-madaminov-/" tabindex="0">
                    <i class="fab fa-linkedin-in btn-icon-inner"></i>
                  </a>
                </li>
  
                <li class="list-inline-item mx-0">
                  <a class="btn btn-sm btn-icon btn-soft-secondary text-gray-400" href="https://github.com/ravshanbekio" tabindex="0">
                    <i class="fab fa-github btn-icon-inner"></i>
                  </a>
                </li>
  
              </ul>
              <p class="mb-0">Copyright © RavshanEnergy 2023. All rights reserved.</p>
            </div>
          </div>
        </div>
      </footer>
  
      <!-- Libs JS -->
      <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
      <script src="{% static 'assets/vendor/popper.js/dist/popper.min.js' %}"></script>
      <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'assets/vendor/jquery-validation/dist/jquery.validate.min.js' %}"></script>
      <script src="{% static 'assets/vendor/jquery-form/dist/jquery.form.min.js' %}"></script>
      <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
      <script src="{% static 'assets/vendor/isotope/dist/isotope.pkgd.min.js' %}"></script>
      <script src="{% static 'assets/vendor/featherlight/featherlight.min.js' %}"></script>
      <script src="{% static 'assets/vendor/featherlight/jquery.detect_swipe.js' %}"></script>
      <script src="{% static 'assets/vendor/featherlight/featherlight.gallery.min.js' %}"></script>
      <script src="{% static 'assets/vendor/jquery.scrollTo/jquery.scrollTo.min.js' %}"></script>
      <script src="{% static 'assets/vendor/jQuery.countdown/dist/jquery.countdown.min.js' %}"></script>
      <script src="{% static 'assets/vendor/typed.js/typed.min.js' %}"></script>
  
      <!-- Theme JS -->
      <script src="{% static 'assets/js/main.js' %}"></script>
  
    </body>
  
</html>

templates/navbar.html
{% load i18n %}
{% load static %}
<!-- Site navigation -->
<nav id="siteNavbar" class="site-navbar site-navbar-transparent navbar navbar-expand-lg navbar-dark fixed-top bg-white shadow-light px-lg-4" data-navbar-base="navbar-dark" data-navbar-toggled="navbar-light" data-navbar-scrolled="navbar-light">

    <!-- Brand -->
    <a class="navbar-brand" href="{% url 'blog:index' %}">
      <img src="assets/images/logo-white.png" class="navbar-brand-img navbar-brand-img-light" alt="">
      <img src="assets/images/logo-dark.png" class="navbar-brand-img navbar-brand-img-dark" alt="">
    </a>

    <!-- Toggler -->
    <button class="navbar-toggler-alternative" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-alternative-icon">
        <span></span>
      </span>
    </button>

    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="navbarCollapse">

      <!-- Navigation -->
      <ul class="navbar-nav ml-auto" id="navigation">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
            Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'portfolio:dashboard' %}" role="button" aria-haspopup="true" aria-expanded="false">
            Portfolio
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'academy:dashboard' %}" role="button" aria-haspopup="true" aria-expanded="false">
            Academy
          </a>
        </li>
      </ul>

      <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <option value="{{ language.code }}"{% if languange.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" class="btn btn-primary" value={% blocktrans %}"Go"{% endblocktrans %}>
    </form>

    </div>
  </nav>

  